packages:
  - packages/tools/*
  - website
minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - '@verdaccio/*'
  - 'verdaccio-*'
saveExact: true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - core-js-pure
  - esbuild
