---
name: addon data

on:
  workflow_dispatch:
  schedule:
    # once per week on Wednesday
    - cron: "0 0 * * 3"

permissions:
  contents: write

jobs:
  update-addons:
    name: Update addon data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Install pnpm
        run: |
          npm install --global corepack@latest
          corepack enable
          corepack install
      - name: Fetch dependencies
        run: pnpm install
      - name: Build Packages
        run: pnpm build
      - name: Update addon data
        run: pnpm script:addon
      - name: format
        run: pnpm format
      - name: Commit & Push changes
        uses: actions-js/push@5a7cbd780d82c0c937b5977586e641b2fd94acc5 # tag=v1.5
        with:
          github_token: ${{ secrets.TOKEN_VERDACCIOBOT_GITHUB }}
          message: "chore: updated addon data"
          branch: master
          author_email: verdaccio.npm@gmail.com
          author_name: verdacciobot
