name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * 0'  # once per week, Sunday 18:00 UTC (~1-2pm US Eastern)

permissions:
  contents: read

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: '.nvmrc'     
      - name: Install pnpm
        run: |
          npm install --global corepack@latest
          corepack enable
          corepack install
      - name: Fetch dependencies
        run: pnpm install
      - name: Check formatting
        run: pnpm format:check
      - name: Lint
        run: pnpm lint
      - name: Build Packages
        run: pnpm build
      - name: Build Translations percentage
        run: pnpm --filter @verdaccio/local-scripts build        
      - name: Build Production
        env:
          CROWDIN_VERDACCIO_API_KEY: ${{ secrets.CROWDIN_VERDACCIO_API_KEY }}
          CONTEXT: production
        run: pnpm --filter @verdaccio/website deploy:build         

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5
        with:
          path: website/build

  deploy:
    name: Deploy to GitHub Pages
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5