name: Test Deploy

on:
  pull_request: 

jobs:
  build:
    name: Build Docusaurus
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: '.nvmrc'
      - name: Config Docusaurus
        run: |
          git config --global user.email "verdacciobot@users.noreply.github.com"
          git config --global user.name "Verdaccio bot for Deployments"
          echo "machine github.com login verdacciobot password ${{ secrets.BOT_TOKEN }}" > ~/.netrc
      - name: Install pnpm
        run: |
          npm install --global corepack@latest
          corepack enable
          corepack install
      - name: Fetch dependencies
        run: pnpm install
      - name: Check formatting
        run: pnpm format:check
      - name: Lint
        run: pnpm lint
      - name: Build Packages
        run: pnpm build
      - name: Build Translations percentage
        run: pnpm --filter @verdaccio/local-scripts build        
      - name: Build Production
        env:
          CROWDIN_VERDACCIO_API_KEY: ${{ secrets.CROWDIN_VERDACCIO_API_KEY }}
          CONTEXT: production
        run: pnpm --filter @verdaccio/website deploy:build:test
